# Generated by Django 5.2.8 on 2025-11-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=10)),
                ('final', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=1)),
                ('color', models.CharField(default='0,0,0', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='personajes/')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
    ]
