# Generated by Django 5.2.8 on 2025-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_alter_personaje_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='velocidad',
            field=models.IntegerField(default=10),
        ),
    ]
